FROM node:20-alpine

WORKDIR /app

# Copy package files and install dependencies
COPY package*.json ./
RUN npm install --production

# Copy rest of the source code
COPY . .

# Expose the port your Express app runs on
EXPOSE 5000

# Start the server
CMD ["node", "src/index.js"]